/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hihonor_aipluginengine_llm_faith_FaithInferWrapper */

#ifndef _Included_com_hihonor_aipluginengine_llm_faith_FaithInferWrapper
#define _Included_com_hihonor_aipluginengine_llm_faith_FaithInferWrapper
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_hihonor_aipluginengine_llm_faith_FaithInferWrapper_unloadModel(JNIEnv *, jobject, jlongArray);
JNIEXPORT jint JNICALL Java_com_hihonor_aipluginengine_llm_faith_FaithInferWrapper_unloadsmModel(JNIEnv *, jobject, jlongArray);
JNIEXPORT jstring JNICALL Java_com_hihonor_aipluginengine_llm_faith_FaithInferWrapper_version(JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_com_hihonor_aipluginengine_llm_faith_FaithInferWrapper_inferBigModel(JNIEnv *, jobject, jlongArray modelAddrs, jbyteArray inputStr, jbyteArray pathStr, jobject llmResultCallback);
JNIEXPORT jlong JNICALL Java_com_hihonor_aipluginengine_llm_faith_FaithInferWrapper_getChatObject(JNIEnv *, jobject);
JNIEXPORT jlongArray JNICALL Java_com_hihonor_aipluginengine_llm_faith_FaithInferWrapper_loadBigModelByPath(JNIEnv* env, jobject thiz, jobjectArray dataPaths);
JNIEXPORT jlongArray JNICALL Java_com_hihonor_aipluginengine_llm_faith_FaithInferWrapper_loadBigModelByPathQNN(JNIEnv* env, jobject thiz, jobjectArray dataPaths, jbyteArray qnnPaths);
JNIEXPORT jlongArray JNICALL Java_com_hihonor_aipluginengine_llm_faith_FaithInferWrapper_loadsmallModelByPath(JNIEnv* env, jobject thiz, jobjectArray dataPaths);
JNIEXPORT jlongArray JNICALL Java_com_hihonor_aipluginengine_llm_faith_FaithInferWrapper_adjustModel(JNIEnv* env, jobject thiz, jlongArray modelAddrs, jobjectArray dataPaths, jint operateType, jint firstIndex);
JNIEXPORT jint JNICALL Java_com_hihonor_aipluginengine_llm_faith_FaithInferWrapper_stopCurTask(JNIEnv* , jobject);
JNIEXPORT jint JNICALL Java_com_hihonor_aipluginengine_llm_faith_FaithInferWrapper_setPriority(JNIEnv* , jobject, jint priorityLevel);
JNICALL jint JNICALL Java_com_hihonor_aipluginengine_llm_faith_FaithInferWrapper_setupPerformance(JNIEnv* , jobject, jint hvxLevel, jint hmxLevel);
JNIEXPORT jint JNICALL Java_com_hihonor_aipluginengine_llm_faith_FaithInferWrapper_setLoraByPath(JNIEnv* env, jobject, jobjectArray lora_paths_2, jobjectArray lora_paths_3, jobjectArray lora_paths_4);


#ifdef __cplusplus
}
#endif
#endif
